services:
  postgres:
    image: postgres:16
    container_name: psigestor_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: psigestor_db
      POSTGRES_USER: psigestor_user
      POSTGRES_PASSWORD: psigestor_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
